set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/src/constraints/zedboard.xdc rfile:../../../../src/constraints/zedboard.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_clocks.xdc id:3 order:LATE scoped_inst:design_1_i/gmii_to_rgmii_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_clocks.xdc id:4 order:LATE scoped_inst:design_1_i/gmii_to_rgmii_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_clocks.xdc id:5 order:LATE scoped_inst:design_1_i/gmii_0_rx_fifo/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0_clocks.xdc id:6 order:LATE scoped_inst:design_1_i/fifo_generator_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1_clocks.xdc id:7 order:LATE scoped_inst:design_1_i/fifo_generator_2/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2_clocks.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2_clocks.xdc id:8 order:LATE scoped_inst:design_1_i/fifo_generator_3/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0.xdc id:9 order:EARLY scoped_inst:design_1_i/gmii_to_rgmii_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0.xdc rfile:../../../zedboard_network_tap.srcs/sources_1/bd/design_1/ip/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0.xdc id:10 order:EARLY scoped_inst:design_1_i/gmii_to_rgmii_1/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G13" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D7" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A13" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B6" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G7" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C4" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A3" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N7" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M7" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R5" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F3" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W2" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G1" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U1" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA3" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA2" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P6" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N4" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M6" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L6" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L7" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J6" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J7" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K5" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K6" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21 [get_ports {rgmii_port_1_rd[0]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports {rgmii_port_1_rd[2]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports rgmii_port_1_rxc]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports rgmii_port_1_rx_ctl]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports reset_port_0]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports {rgmii_port_1_rd[1]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {rgmii_port_1_rd[3]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports rgmii_port_0_rxc]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports rgmii_port_0_rx_ctl]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {rgmii_port_0_rd[2]}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P22 [get_ports {rgmii_port_0_rd[3]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports {rgmii_port_0_td[1]}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22 [get_ports {rgmii_port_0_td[2]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports {rgmii_port_1_td[0]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {rgmii_port_1_td[2]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {rgmii_port_1_td[3]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {rgmii_port_0_rd[0]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {rgmii_port_0_rd[1]}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21 [get_ports {rgmii_port_0_td[0]}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports rgmii_port_0_txc]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {rgmii_port_0_td[3]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports rgmii_port_0_tx_ctl]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {rgmii_port_1_td[1]}]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports rgmii_port_1_txc]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports rgmii_port_1_tx_ctl]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports reset_port_1]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {ref_clk_oe[0]}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {ref_clk_fsel[0]}]
set_property src_info {type:XDC file:2 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ref_clk_fsel_OBUF[0]}]
set_property src_info {type:XDC file:2 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets reset_port_1_OBUF]
set_property src_info {type:XDC file:2 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets reset_port_0_OBUF]
set_property src_info {type:XDC file:2 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ref_clk_oe_OBUF[0]}]
set_property src_info {type:XDC file:2 line:729 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.gpe.rdpe/axis_prog_empty]
set_property src_info {type:XDC file:2 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/axis_prog_empty]
set_property src_info {type:XDC file:2 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gl0.rd/axis_prog_empty]
set_property src_info {type:XDC file:2 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/axis_prog_empty]
set_property src_info {type:XDC file:2 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/fifo_generator_0/U0/axis_prog_empty]
set_property src_info {type:XDC file:2 line:734 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gl0.rd/axis_prog_empty]]
set_property src_info {type:XDC file:2 line:735 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.gpe.rdpe/axis_prog_empty]]
set_property src_info {type:XDC file:2 line:736 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/axis_prog_empty]]
set_property src_info {type:XDC file:2 line:737 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/axis_prog_empty]]
set_property src_info {type:XDC file:2 line:738 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_C]
set_property src_info {type:XDC file:2 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tuser[3]}]
set_property src_info {type:XDC file:2 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[11]}]
set_property src_info {type:XDC file:2 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/s_axis_tuser[3]}]
set_property src_info {type:XDC file:2 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[6]}]
set_property src_info {type:XDC file:2 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[0]}]
set_property src_info {type:XDC file:2 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tready]
set_property src_info {type:XDC file:2 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/backup_marker]
set_property src_info {type:XDC file:2 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tuser[0]}]
set_property src_info {type:XDC file:2 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[12]}]
set_property src_info {type:XDC file:2 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf_i_3_n_0]
set_property src_info {type:XDC file:2 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/s_axis_tuser[1]}]
set_property src_info {type:XDC file:2 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tuser[1]}]
set_property src_info {type:XDC file:2 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tuser[2]}]
set_property src_info {type:XDC file:2 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[8]}]
set_property src_info {type:XDC file:2 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/s_axis_tuser[2]}]
set_property src_info {type:XDC file:2 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/sleep]
set_property src_info {type:XDC file:2 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_2_s_axis_tready]
set_property src_info {type:XDC file:2 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[3]}]
set_property src_info {type:XDC file:2 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[1]}]
set_property src_info {type:XDC file:2 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_underflow]
set_property src_info {type:XDC file:2 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_empty]
set_property src_info {type:XDC file:2 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[12]}]
set_property src_info {type:XDC file:2 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[3]}]
set_property src_info {type:XDC file:2 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/<const0>]
set_property src_info {type:XDC file:2 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[6]}]
set_property src_info {type:XDC file:2 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[11]}]
set_property src_info {type:XDC file:2 line:770 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/s_axis_tuser[0]}]
set_property src_info {type:XDC file:2 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[6]}]
set_property src_info {type:XDC file:2 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[10]}]
set_property src_info {type:XDC file:2 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[7]}]
set_property src_info {type:XDC file:2 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[2]}]
set_property src_info {type:XDC file:2 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tuser[3]}]
set_property src_info {type:XDC file:2 line:779 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[10]}]
set_property src_info {type:XDC file:2 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tuser[3]}]
set_property src_info {type:XDC file:2 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/backup]
set_property src_info {type:XDC file:2 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[4]}]
set_property src_info {type:XDC file:2 line:783 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_aclk]
set_property src_info {type:XDC file:2 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tuser[0]}]
set_property src_info {type:XDC file:2 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[1]}]
set_property src_info {type:XDC file:2 line:787 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/p_0_in]
set_property src_info {type:XDC file:2 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[4]}]
set_property src_info {type:XDC file:2 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/m_axis_tready]
set_property src_info {type:XDC file:2 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tuser[2]}]
set_property src_info {type:XDC file:2 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_injectdbiterr]
set_property src_info {type:XDC file:2 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[11]}]
set_property src_info {type:XDC file:2 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[9]}]
set_property src_info {type:XDC file:2 line:803 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[2]}]
set_property src_info {type:XDC file:2 line:804 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/s_axis_tvalid]
set_property src_info {type:XDC file:2 line:805 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/m_aclk]
set_property src_info {type:XDC file:2 line:806 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[0]}]
set_property src_info {type:XDC file:2 line:807 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[9]}]
set_property src_info {type:XDC file:2 line:808 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[6]}]
set_property src_info {type:XDC file:2 line:809 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[3]}]
set_property src_info {type:XDC file:2 line:811 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[1]}]
set_property src_info {type:XDC file:2 line:828 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:830 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[4]}]
set_property src_info {type:XDC file:2 line:832 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:836 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[7]}]
set_property src_info {type:XDC file:2 line:837 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[2]}]
set_property src_info {type:XDC file:2 line:838 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:839 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[6]}]
set_property src_info {type:XDC file:2 line:840 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:854 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:855 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:872 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[0]}]
set_property src_info {type:XDC file:2 line:874 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_3]
set_property src_info {type:XDC file:2 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[6]}]
set_property src_info {type:XDC file:2 line:879 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/GMII_1_fifo_prog_empty]
set_property src_info {type:XDC file:2 line:890 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/Op1]
set_property src_info {type:XDC file:2 line:895 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[2]}]
set_property src_info {type:XDC file:2 line:901 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[3]}]
set_property src_info {type:XDC file:2 line:923 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/not_gate_full_fifo_1_n_0]
set_property src_info {type:XDC file:2 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_9]
set_property src_info {type:XDC file:2 line:926 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[3]}]
set_property src_info {type:XDC file:2 line:931 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/or_gate_wr_en_fifo_1_Res]
set_property src_info {type:XDC file:2 line:933 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[6]}]
set_property src_info {type:XDC file:2 line:941 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_6]
set_property src_info {type:XDC file:2 line:955 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_4]
set_property src_info {type:XDC file:2 line:957 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_7]
set_property src_info {type:XDC file:2 line:960 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_2]
set_property src_info {type:XDC file:2 line:961 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:963 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/GMII_0_fifo_prog_empty]
set_property src_info {type:XDC file:2 line:966 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[4]}]
set_property src_info {type:XDC file:2 line:967 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tuser[2]}]
set_property src_info {type:XDC file:2 line:968 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[0]}]
set_property src_info {type:XDC file:2 line:969 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[3]}]
set_property src_info {type:XDC file:2 line:970 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/s_aclk]
set_property src_info {type:XDC file:2 line:971 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/axis_prog_full]
set_property src_info {type:XDC file:2 line:972 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[4]}]
set_property src_info {type:XDC file:2 line:973 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[2]}]
set_property src_info {type:XDC file:2 line:974 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[11]}]
set_property src_info {type:XDC file:2 line:976 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:978 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/m_axis_tvalid]
set_property src_info {type:XDC file:2 line:979 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[1]}]
set_property src_info {type:XDC file:2 line:980 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[1]}]
set_property src_info {type:XDC file:2 line:981 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_aresetn]
set_property src_info {type:XDC file:2 line:986 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:991 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[1]}]
set_property src_info {type:XDC file:2 line:995 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[7]}]
set_property src_info {type:XDC file:2 line:997 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[8]}]
set_property src_info {type:XDC file:2 line:999 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[2]}]
set_property src_info {type:XDC file:2 line:1000 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:1002 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[2]}]
set_property src_info {type:XDC file:2 line:1003 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tuser[0]}]
set_property src_info {type:XDC file:2 line:1004 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[11]}]
set_property src_info {type:XDC file:2 line:1009 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[5]}]
set_property src_info {type:XDC file:2 line:1015 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[2]}]
set_property src_info {type:XDC file:2 line:1017 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[8]}]
set_property src_info {type:XDC file:2 line:1018 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[0]}]
set_property src_info {type:XDC file:2 line:1019 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:1020 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[10]}]
set_property src_info {type:XDC file:2 line:1021 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[3]}]
set_property src_info {type:XDC file:2 line:1024 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:1025 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[5]}]
set_property src_info {type:XDC file:2 line:1026 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[8]}]
set_property src_info {type:XDC file:2 line:1027 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:1028 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tuser[3]}]
set_property src_info {type:XDC file:2 line:1030 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:1031 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tuser[0]}]
set_property src_info {type:XDC file:2 line:1032 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[7]}]
set_property src_info {type:XDC file:2 line:1035 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/<const1>]
set_property src_info {type:XDC file:2 line:1036 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:1038 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[9]}]
set_property src_info {type:XDC file:2 line:1039 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_5]
set_property src_info {type:XDC file:2 line:1041 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[8]}]
set_property src_info {type:XDC file:2 line:1042 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0_m_axis_tvalid]
set_property src_info {type:XDC file:2 line:1046 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/s_aresetn]
set_property src_info {type:XDC file:2 line:1047 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[1]}]
set_property src_info {type:XDC file:2 line:1049 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/int_clk]
set_property src_info {type:XDC file:2 line:1050 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[7]}]
set_property src_info {type:XDC file:2 line:1051 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[5]}]
set_property src_info {type:XDC file:2 line:1053 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/axis_prog_empty]
set_property src_info {type:XDC file:2 line:1054 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/s_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:1055 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tuser[1]}]
set_property src_info {type:XDC file:2 line:1056 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[4]}]
set_property src_info {type:XDC file:2 line:1058 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[5]}]
set_property src_info {type:XDC file:2 line:1059 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[9]}]
set_property src_info {type:XDC file:2 line:1062 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:1063 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[1]}]
set_property src_info {type:XDC file:2 line:1064 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:1065 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[1]}]
set_property src_info {type:XDC file:2 line:1066 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[10]}]
set_property src_info {type:XDC file:2 line:1068 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty]
set_property src_info {type:XDC file:2 line:1069 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[5]}]
set_property src_info {type:XDC file:2 line:1070 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[2]}]
set_property src_info {type:XDC file:2 line:1071 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[5]}]
set_property src_info {type:XDC file:2 line:1072 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/s_axis_tready]
set_property src_info {type:XDC file:2 line:1073 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:1075 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[0]}]
set_property src_info {type:XDC file:2 line:1077 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tuser[1]}]
set_property src_info {type:XDC file:2 line:1078 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:1079 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[5]}]
set_property src_info {type:XDC file:2 line:1080 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:1081 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[4]}]
set_property src_info {type:XDC file:2 line:1082 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[7]}]
set_property src_info {type:XDC file:2 line:1083 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf_i_2_n_0]
set_property src_info {type:XDC file:2 line:1085 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[10]}]
set_property src_info {type:XDC file:2 line:1089 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_wr_data_count[8]}]
set_property src_info {type:XDC file:2 line:1090 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[9]}]
set_property src_info {type:XDC file:2 line:1091 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[10]}]
set_property src_info {type:XDC file:2 line:1092 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[9]}]
set_property src_info {type:XDC file:2 line:1093 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[5]}]
set_property src_info {type:XDC file:2 line:1096 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:1097 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tuser[2]}]
set_property src_info {type:XDC file:2 line:1098 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:1099 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[0]}]
set_property src_info {type:XDC file:2 line:1102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:1103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[8]}]
set_property src_info {type:XDC file:2 line:1104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[3]}]
set_property src_info {type:XDC file:2 line:1105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/m_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:1106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_wr_data_count[12]}]
set_property src_info {type:XDC file:2 line:1107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_3_n_8]
set_property src_info {type:XDC file:2 line:1108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full_thresh[0]}]
set_property src_info {type:XDC file:2 line:1113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[12]}]
set_property src_info {type:XDC file:2 line:1115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[7]}]
set_property src_info {type:XDC file:2 line:1116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tuser[1]}]
set_property src_info {type:XDC file:2 line:1117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:1125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_txd[7]}]
set_property src_info {type:XDC file:2 line:1127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_sbiterr]
set_property src_info {type:XDC file:2 line:1128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tready]
set_property src_info {type:XDC file:2 line:1129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[0]}]
set_property src_info {type:XDC file:2 line:1130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/util_vector_logic_1_Res]
set_property src_info {type:XDC file:2 line:1131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_rd_data_count[3]}]
set_property src_info {type:XDC file:2 line:1132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/m_axis_tvalid]
set_property src_info {type:XDC file:2 line:1134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[6]}]
set_property src_info {type:XDC file:2 line:1135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[12]}]
set_property src_info {type:XDC file:2 line:1136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[6]}]
set_property src_info {type:XDC file:2 line:1137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/<const0>]
set_property src_info {type:XDC file:2 line:1139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[11]}]
set_property src_info {type:XDC file:2 line:1140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[10]}]
set_property src_info {type:XDC file:2 line:1141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_empty_thresh[4]}]
set_property src_info {type:XDC file:2 line:1142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_prog_full]
set_property src_info {type:XDC file:2 line:1143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_aclk]
set_property src_info {type:XDC file:2 line:1144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_overflow]
set_property src_info {type:XDC file:2 line:1145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[7]}]
set_property src_info {type:XDC file:2 line:1146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/inverted_reset]
set_property src_info {type:XDC file:2 line:1147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_dbiterr]
set_property src_info {type:XDC file:2 line:1148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_injectsbiterr]
set_property src_info {type:XDC file:2 line:1149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/U0/inst_fifo_gen/axis_data_count[9]}]
set_property src_info {type:XDC file:2 line:1152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/fifo_generator_0/axis_rd_data_count[11]}]
set_property src_info {type:XDC file:2 line:1155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[4]}]
set_property src_info {type:XDC file:2 line:1156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/gmii_to_rgmii_1_gmii_rxd[5]}]
set_property src_info {type:XDC file:2 line:1157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/fifo_generator_0/U0/inst_fifo_gen/s_axis_tvalid]
set_property src_info {type:SCOPED_XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks design_1_gmii_to_rgmii_0_0_rgmii_rx_clk] -rise_to [get_clocks [get_clocks -of_objects [get_ports rgmii_port_0_rxc]]] -hold
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks design_1_gmii_to_rgmii_0_0_rgmii_rx_clk] -fall_to [get_clocks -of_objects [get_ports rgmii_port_0_rxc]] -hold
set_property src_info {type:SCOPED_XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks -of_objects [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/O]] -fall_to [get_clocks rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks -of_objects [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/O]] -rise_to [get_clocks rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks design_1_gmii_to_rgmii_1_0_rgmii_rx_clk] -rise_to [get_clocks [get_clocks -of_objects [get_ports rgmii_port_1_rxc]]] -hold
set_property src_info {type:SCOPED_XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks design_1_gmii_to_rgmii_1_0_rgmii_rx_clk] -fall_to [get_clocks -of_objects [get_ports rgmii_port_1_rxc]] -hold
set_property src_info {type:SCOPED_XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -fall_from [get_clocks -of_objects [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/O]] -fall_to [get_clocks rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -rise_from [get_clocks -of_objects [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/O]] -rise_to [get_clocks rgmii_tx_clk] -hold
set_property src_info {type:SCOPED_XDC file:5 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/gmii_0_rx_fifo/U0/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/gmii_0_rx_fifo/U0/s_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_1/U0/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_1/U0/s_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_2/U0/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_2/U0/s_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_3/U0/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/fifo_generator_3/U0/s_aclk]]]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/CE0]
set_property src_info {type:SCOPED_XDC file:9 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/S0]
set_property src_info {type:SCOPED_XDC file:9 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/CE1]
set_property src_info {type:SCOPED_XDC file:9 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins design_1_i/gmii_to_rgmii_0/U0/i_gmii_to_rgmii_block/i_bufgmux_gmii_clk/S1]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/CE0]
set_property src_info {type:SCOPED_XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/S0]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/CE1]
set_property src_info {type:SCOPED_XDC file:10 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins design_1_i/gmii_to_rgmii_1/U0/i_bufgmux_gmii_clk/S1]
