# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_ooc.xdc

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/design_1_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_0_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_0_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/design_1_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_1_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_1_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_0 || ORIG_REF_NAME==design_1_fifo_generator_1_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_link_status_and_gate_0/design_1_link_status_and_gate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_link_status_and_gate_0 || ORIG_REF_NAME==design_1_link_status_and_gate_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_0_0/design_1_or_gate_wr_en_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_gate_wr_en_fifo_0_0 || ORIG_REF_NAME==design_1_or_gate_wr_en_fifo_0_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_1_0/design_1_or_gate_wr_en_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_gate_wr_en_fifo_1_0 || ORIG_REF_NAME==design_1_or_gate_wr_en_fifo_1_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_0_0/design_1_not_gate_full_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_not_gate_full_fifo_0_0 || ORIG_REF_NAME==design_1_not_gate_full_fifo_0_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_1_0/design_1_not_gate_full_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_not_gate_full_fifo_1_0 || ORIG_REF_NAME==design_1_not_gate_full_fifo_1_0}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_1 || ORIG_REF_NAME==design_1_fifo_generator_1_1}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_2 || ORIG_REF_NAME==design_1_fifo_generator_1_2}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1}]

# IP: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0}]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_0_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_0_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_0_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_0_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_ooc.xdc

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_1_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_1_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_1_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_1_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_ooc.xdc

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_0 || ORIG_REF_NAME==design_1_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_0 || ORIG_REF_NAME==design_1_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_1 || ORIG_REF_NAME==design_1_fifo_generator_1_1}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_1 || ORIG_REF_NAME==design_1_fifo_generator_1_1}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_2 || ORIG_REF_NAME==design_1_fifo_generator_1_2}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_1_2 || ORIG_REF_NAME==design_1_fifo_generator_1_2}] {/U0 }]/U0 ]]
