# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.tmp/rgmii_to_axis_fifo_v1_0_v1_0_project/rgmii_to_axis_fifo_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.tmp/rgmii_to_axis_fifo_v1_0_v1_0_project/rgmii_to_axis_fifo_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo [current_project]
read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/design_1_gmii_to_rgmii_0_0.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/synth/design_1_gmii_to_rgmii_0_0_ooc.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_0_0/design_1_gmii_to_rgmii_0_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/design_1_gmii_to_rgmii_1_0.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/synth/design_1_gmii_to_rgmii_1_0_ooc.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_gmii_to_rgmii_1_0/design_1_gmii_to_rgmii_1_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_0/design_1_fifo_generator_1_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_link_status_and_gate_0/design_1_link_status_and_gate_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_link_status_and_gate_0/design_1_link_status_and_gate_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_0_0/design_1_or_gate_wr_en_fifo_0_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_0_0/design_1_or_gate_wr_en_fifo_0_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_1_0/design_1_or_gate_wr_en_fifo_1_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_or_gate_wr_en_fifo_1_0/design_1_or_gate_wr_en_fifo_1_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_0_0/design_1_not_gate_full_fifo_0_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_0_0/design_1_not_gate_full_fifo_0_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_1_0/design_1_not_gate_full_fifo_1_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_not_gate_full_fifo_1_0/design_1_not_gate_full_fifo_1_0.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_1/design_1_fifo_generator_1_1.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_fifo_generator_1_2/design_1_fifo_generator_1_2.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci]

read_ip -quiet /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci]

read_vhdl -library xil_defaultlib /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/rgmii_to_axis_fifo.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_ooc.xdc
set_property used_in_implementation false [get_files /home/brett/workspace/Vivado_WS/network-tap-no-ps7/ip_repo/src/design_1_ooc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top rgmii_to_axis_fifo -part xc7z020clg484-1


write_checkpoint -force -noxdef rgmii_to_axis_fifo.dcp

catch { report_utilization -file rgmii_to_axis_fifo_utilization_synth.rpt -pb rgmii_to_axis_fifo_utilization_synth.pb }
