# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/src/constraints/zedboard.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_0/design_1_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_0 || ORIG_REF_NAME==design_1_util_reduced_logic_0_0}]

# IP: bd/design_1/ip/design_1_util_reduced_logic_1_0/design_1_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_1_0 || ORIG_REF_NAME==design_1_util_reduced_logic_1_0}]

# IP: bd/design_1/ip/design_1_ref_clk_oe_0/design_1_ref_clk_oe_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ref_clk_oe_0 || ORIG_REF_NAME==design_1_ref_clk_oe_0}]

# IP: bd/design_1/ip/design_1_ref_clk_fsel_0/design_1_ref_clk_fsel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ref_clk_fsel_0 || ORIG_REF_NAME==design_1_ref_clk_fsel_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/design_1_gmii_to_rgmii_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gmii_to_rgmii_axis_0_0 || ORIG_REF_NAME==design_1_gmii_to_rgmii_axis_0_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_1_0/gmii_to_rgmii_axis_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_2_0/gmii_to_rgmii_axis_fifo_generator_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_3_0/gmii_to_rgmii_axis_fifo_generator_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_0_rx_fifo_0/gmii_to_rgmii_axis_gmii_0_rx_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_0_0/gmii_to_rgmii_axis_gmii_to_rgmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_1_0/gmii_to_rgmii_axis_gmii_to_rgmii_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_link_status_and_gate_0/gmii_to_rgmii_axis_link_status_and_gate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_link_status_and_gate_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_link_status_and_gate_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_not_gate_full_fifo_0_0/gmii_to_rgmii_axis_not_gate_full_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_not_gate_full_fifo_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_not_gate_full_fifo_0_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_not_gate_full_fifo_1_0/gmii_to_rgmii_axis_not_gate_full_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_not_gate_full_fifo_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_not_gate_full_fifo_1_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_or_gate_wr_en_fifo_0_0/gmii_to_rgmii_axis_or_gate_wr_en_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_or_gate_wr_en_fifo_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_or_gate_wr_en_fifo_0_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_or_gate_wr_en_fifo_1_0/gmii_to_rgmii_axis_or_gate_wr_en_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_or_gate_wr_en_fifo_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_or_gate_wr_en_fifo_1_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_util_vector_logic_0_0/gmii_to_rgmii_axis_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_util_vector_logic_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_util_vector_logic_0_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_util_vector_logic_1_0/gmii_to_rgmii_axis_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_util_vector_logic_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_util_vector_logic_1_0}]

# IP: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_util_vector_logic_2_0/gmii_to_rgmii_axis_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_util_vector_logic_2_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_util_vector_logic_2_0}]

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_1_0/gmii_to_rgmii_axis_fifo_generator_1_0/gmii_to_rgmii_axis_fifo_generator_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_1_0/gmii_to_rgmii_axis_fifo_generator_1_0/gmii_to_rgmii_axis_fifo_generator_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_2_0/gmii_to_rgmii_axis_fifo_generator_2_0/gmii_to_rgmii_axis_fifo_generator_2_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_2_0/gmii_to_rgmii_axis_fifo_generator_2_0/gmii_to_rgmii_axis_fifo_generator_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_2_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_3_0/gmii_to_rgmii_axis_fifo_generator_3_0/gmii_to_rgmii_axis_fifo_generator_3_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_fifo_generator_3_0/gmii_to_rgmii_axis_fifo_generator_3_0/gmii_to_rgmii_axis_fifo_generator_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_fifo_generator_3_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_0_rx_fifo_0/gmii_to_rgmii_axis_gmii_0_rx_fifo_0/gmii_to_rgmii_axis_gmii_0_rx_fifo_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_0_rx_fifo_0/gmii_to_rgmii_axis_gmii_0_rx_fifo_0/gmii_to_rgmii_axis_gmii_0_rx_fifo_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_0_rx_fifo_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_0_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_0_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_0_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_1_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_1_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0 || ORIG_REF_NAME==gmii_to_rgmii_axis_gmii_to_rgmii_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_gmii_to_rgmii_1_0/synth/gmii_to_rgmii_axis_gmii_to_rgmii_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_gmii_to_rgmii_axis_0_0/src/gmii_to_rgmii_axis_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
