# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/gmii_to_rgmii_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_0 || ORIG_REF_NAME==gmii_to_rgmii_0}]

# XDC: /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_0 || ORIG_REF_NAME==gmii_to_rgmii_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gmii_to_rgmii_0 || ORIG_REF_NAME==gmii_to_rgmii_0}] {/U0 }]/U0 ]]

# XDC: /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0_ooc.xdc
