# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.tmp/gmii2axis_v1_1_project/gmii2axis_v1_1_project.cache/wt [current_project]
set_property parent.project_path /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/zedboard_network_tap/zedboard_network_tap.tmp/gmii2axis_v1_1_project/gmii2axis_v1_1_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0
  /home/brett/workspace/Vivado_WS/HLS_Tutorials/2016.1/Interface_Synthesis/lab4/axi_interfaces_prj/solution1/impl/ip
} [current_project]
read_ip -quiet /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/gmii_to_rgmii_0.xci
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/synth/gmii_to_rgmii_0_ooc.xdc]
set_property is_locked true [get_files /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/src/gmii_to_rgmii_0/gmii_to_rgmii_0.xci]

read_vhdl -library xil_defaultlib /home/brett/workspace/Vivado_WS/ethernet-fmc-network-tap/Vivado/ip_repo/gmii2axis_1.0/hdl/gmii2axis_v1_0.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top gmii2axis_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef gmii2axis_v1_0.dcp

catch { report_utilization -file gmii2axis_v1_0_utilization_synth.rpt -pb gmii2axis_v1_0_utilization_synth.pb }
